"""Writing .wui scenarios and the small companion files the cases need."""

import os


def write_wui(path, sections):
    """`sections` is a list of (header, [(key, value) or bare row string]); a header may repeat (repeatable
    sections such as [Destination])."""
    lines = ["# Generated by Verification/generate.py - see the case's README.md for what it checks."]
    for header, entries in sections:
        lines.append("")
        lines.append("[%s]" % header)
        for e in entries:
            if isinstance(e, tuple):
                lines.append("%s=%s" % e)
            else:
                lines.append(str(e))
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def latlon(p):
    return "%.9f,%.9f" % p


def write_population(path, households):
    """households: [(home (lat, lon), access (lat, lon), people)]."""
    with open(path, "w") as f:
        f.write("OriginLat,OriginLon,AccessLat,AccessLon,People\n")
        for home, access, people in households:
            f.write("%.9f,%.9f,%.9f,%.9f,%d\n" % (home[0], home[1], access[0], access[1], people))


def write_group_mask(path, x_sim, y_sim, width, height, cell):
    """An evacuation-group area mask (.asc in SIMULATION coordinates - metres from the domain's south-west corner,
    as the GUI's group painter writes them) covering the box [x_sim, x_sim + width] x [y_sim, y_sim + height]."""
    ncols = int(round(width / cell))
    nrows = int(round(height / cell))
    with open(path, "w") as f:
        f.write("ncols %d\nnrows %d\nxllcorner %.3f\nyllcorner %.3f\ncellsize %.3f\nNODATA_value -9999\n"
                % (ncols, nrows, x_sim, y_sim, cell))
        row = " ".join(["1"] * ncols) + "\n"
        for _ in range(nrows):
            f.write(row)


def write_sumo_config(folder, net_name, cfg_name="network.sumocfg"):
    """A SUMO configuration like the one the GUI's Roads step writes (network only, ignore-route-errors), plus a
    vehicle type with SUMO's driver imperfection (sigma) and speed deviation (speedDev) set to 0, so that a car's
    travel time is the road's length over its speed limit plus acceleration - an expectation that can be stated
    without SUMO. Everything else about DEFAULT_VEHTYPE (accel 2.6 m/s2, length 5 m, ...) is SUMO's default."""
    with open(os.path.join(folder, "vtypes.add.xml"), "w") as f:
        f.write('<additional>\n    <!-- deterministic drivers: no dawdling (sigma) and every car at the speed limit '
                '(speedDev) -->\n    <vType id="DEFAULT_VEHTYPE" sigma="0" speedDev="0"/>\n</additional>\n')
    with open(os.path.join(folder, cfg_name), "w") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n<sumoConfiguration>\n    <input>\n'
                '        <net-file value="%s"/>\n        <additional-files value="vtypes.add.xml"/>\n    </input>\n'
                '    <processing>\n        <ignore-route-errors value="true"/>\n    </processing>\n'
                '    <report>\n        <no-step-log value="true"/>\n    </report>\n</sumoConfiguration>\n' % net_name)
    return os.path.join(folder, cfg_name)
